<?php
if (! defined ( 'BASEPATH' ))
	exit ( 'No direct script access allowed' );

if (ENVIRONMENT === 'production')
{
	$config ['log_threshold'] = 1; // 日志配置
} elseif (ENVIRONMENT === 'checkout')
{
	$config ['log_threshold'] = 5; // 日志配置
} else
{
	$config ['log_threshold'] = 5; // 日志配置
}

/*
 * |-------------------------------------------------------------------------- | Base Site URL |-------------------------------------------------------------------------- | | URL to your CodeIgniter root. Typically this will be your base URL, | WITH a trailing slash: | |	http://example.com/ | | If this is not set then CodeIgniter will guess the protocol, domain and | path to your installation. |
 */
$config ['base_url'] = '//888.166cai.cn/dashboard';
$config ['site_url'] = '//888.166cai.cn';

/*
 * |-------------------------------------------------------------------------- | Index File |-------------------------------------------------------------------------- | | Typically this will be your index.php file, unless you've renamed it to | something else. If you are using mod_rewrite to remove the page set this | variable so that it is blank. |
 */
$config ['index_page'] = 'index.php';

/*
 * |-------------------------------------------------------------------------- | URI PROTOCOL |-------------------------------------------------------------------------- | | This item determines which server global should be used to retrieve the | URI string. The default setting of 'AUTO' works for most servers. | If your links do not seem to work, try one of the other delicious flavors: | | 'AUTO'			Default - auto detects | 'PATH_INFO'		Uses the PATH_INFO | 'QUERY_STRING'	Uses the QUERY_STRING | 'REQUEST_URI'		Uses the REQUEST_URI | 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO |
 */
$config ['uri_protocol'] = 'AUTO';

/*
 * |-------------------------------------------------------------------------- | URL suffix |-------------------------------------------------------------------------- | | This option allows you to add a suffix to all URLs generated by CodeIgniter. | For more information please see the user guide: | | http://codeigniter.com/user_guide/general/urls.html
 */

$config ['url_suffix'] = '';

/*
 * |-------------------------------------------------------------------------- | Default Language |-------------------------------------------------------------------------- | | This determines which set of language files should be used. Make sure | there is an available translation if you intend to use something other | than english. |
 */
$config ['language'] = 'english';

/*
 * |-------------------------------------------------------------------------- | Default Character Set |-------------------------------------------------------------------------- | | This determines which character set is used by default in various methods | that require a character set to be provided. |
 */
$config ['charset'] = 'UTF-8';

/*
 * |-------------------------------------------------------------------------- | Enable/Disable System Hooks |-------------------------------------------------------------------------- | | If you would like to use the 'hooks' feature you must enable it by | setting this variable to TRUE (boolean). See the user guide for details. |
 */
$config ['enable_hooks'] = TRUE;

/*
 * |-------------------------------------------------------------------------- | Class Extension Prefix |-------------------------------------------------------------------------- | | This item allows you to set the filename/classname prefix when extending | native libraries. For more information please see the user guide: | | http://codeigniter.com/user_guide/general/core_classes.html | http://codeigniter.com/user_guide/general/creating_libraries.html |
 */
$config ['subclass_prefix'] = 'MY_';

/*
 * |-------------------------------------------------------------------------- | Allowed URL Characters |-------------------------------------------------------------------------- | | This lets you specify with a regular expression which characters are permitted | within your URLs. When someone tries to submit a URL with disallowed | characters they will get a warning message. | | As a security measure you are STRONGLY encouraged to restrict URLs to | as few characters as possible. By default only these are allowed: a-z 0-9~%.:_- | | Leave blank to allow all characters -- but only if you are insane. | | DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!! |
 */
$config ['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
 * |-------------------------------------------------------------------------- | Enable Query Strings |-------------------------------------------------------------------------- | | By default CodeIgniter uses search-engine friendly segment based URLs: | example.com/who/what/where/ | | By default CodeIgniter enables access to the $_GET array. If for some | reason you would like to disable it, set 'allow_get_array' to FALSE. | | You can optionally enable standard query string based URLs: | example.com?who=me&what=something&where=here | | Options are: TRUE or FALSE (boolean) | | The other items let you set the query string 'words' that will | invoke your controllers and its functions: | example.com/index.php?c=controller&m=function | | Please note that some of the helpers won't work as expected when | this feature is enabled, since CodeIgniter is designed primarily to | use segment based URLs. |
 */
$config ['allow_get_array'] = TRUE;
$config ['enable_query_strings'] = FALSE;
$config ['controller_trigger'] = 'c';
$config ['function_trigger'] = 'm';
$config ['directory_trigger'] = 'd'; // experimental not currently in use

/*
 * |-------------------------------------------------------------------------- | Error Logging Threshold |-------------------------------------------------------------------------- | | If you have enabled error logging, you can set an error threshold to | determine what gets logged. Threshold options are: | You can enable error logging by setting a threshold over zero. The | threshold determines what gets logged. Threshold options are: | |	0 = Disables logging, Error logging TURNED OFF | 1 = Log Messages |	2 = Error Messages (including PHP errors) |	3 = Debug Messages |	4 = Informational Messages |	5 = All Messages | | For a live site you'll usually only enable Errors (1) to be logged otherwise | your log files will fill up very fast. | $config['log_threshold'] = 5;
 */


/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config ['log_path'] = '';
$config['base_path'] = dirname(BASEPATH);
/*
 * |-------------------------------------------------------------------------- | Date Format for Logs |-------------------------------------------------------------------------- | | Each item that is logged has an associated date. You can use PHP date | codes to set your own date formatting |
 */
$config ['log_date_format'] = 'Y-m-d H:i:s';

/*
 * |-------------------------------------------------------------------------- | Cache Directory Path |-------------------------------------------------------------------------- | | Leave this BLANK unless you would like to set something other than the default | system/cache/ folder. Use a full server path with trailing slash. |
 */
$config ['cache_path'] = '';

/*
 * |-------------------------------------------------------------------------- | Encryption Key |-------------------------------------------------------------------------- | | If you use the Encryption class or the Session class you | MUST set an encryption key. See the user guide for info. |
 */
$config ['encryption_key'] = 'caipiao-2345-com';

/*
 * |-------------------------------------------------------------------------- | Session Variables |-------------------------------------------------------------------------- | | 'sess_cookie_name'		= the name you want for the cookie | 'sess_expiration'			= the number of SECONDS you want the session to last. | by default sessions last 7200 seconds (two hours). Set to zero for no expiration. | 'sess_expire_on_close'	= Whether to cause the session to expire automatically | when the browser window is closed | 'sess_encrypt_cookie'		= Whether to encrypt the cookie | 'sess_use_database'		= Whether to save the session data to a database | 'sess_table_name'			= The name of the session database table | 'sess_match_ip'			= Whether to match the user's IP address when reading the session data | 'sess_match_useragent'	= Whether to match the User Agent when reading the session data | 'sess_time_to_update'		= how many seconds between CI refreshing Session Information |
 */
$config ['sess_cookie_name'] = 'ci_session';
$config ['sess_expiration'] = 7200;
$config ['sess_expire_on_close'] = TRUE;
$config ['sess_encrypt_cookie'] = TRUE;
$config ['sess_use_database'] = FALSE;
$config ['sess_table_name'] = 'ci_sessions';
$config ['sess_match_ip'] = FALSE;
$config ['sess_match_useragent'] = TRUE;
$config ['sess_time_to_update'] = 300;

/*
 * |-------------------------------------------------------------------------- | Cookie Related Variables |-------------------------------------------------------------------------- | | 'cookie_prefix' = Set a prefix if you need to avoid collisions | 'cookie_domain' = Set to .your-domain.com for site-wide cookies | 'cookie_path' = Typically will be a forward slash | 'cookie_secure' = Cookies will only be set if a secure HTTPS connection exists. |
 */
$config ['cookie_prefix'] = "";
$config ['cookie_domain'] = "";
$config ['cookie_path'] = "/";
$config ['cookie_secure'] = FALSE;

/*
 * |-------------------------------------------------------------------------- | Global XSS Filtering |-------------------------------------------------------------------------- | | Determines whether the XSS filter is always active when GET, POST or | COOKIE data is encountered |
 */
$config ['global_xss_filtering'] = FALSE;

/*
 * |-------------------------------------------------------------------------- | Cross Site Request Forgery |-------------------------------------------------------------------------- | Enables a CSRF cookie token to be set. When set to TRUE, token will be | checked on a submitted form. If you are accepting user data, it is strongly | recommended CSRF protection be enabled. | | 'csrf_token_name' = The token name | 'csrf_cookie_name' = The cookie name | 'csrf_expire' = The number in seconds the token should expire.
 */
$config ['csrf_protection'] = FALSE;
$config ['csrf_token_name'] = 'csrf_test_name';
$config ['csrf_cookie_name'] = 'csrf_cookie_name';
$config ['csrf_expire'] = 7200;

/*
 * |-------------------------------------------------------------------------- | Output Compression |-------------------------------------------------------------------------- | | Enables Gzip output compression for faster page loads. When enabled, | the output class will test whether your server supports Gzip. | Even if it does, however, not all browsers support compression | so enable only if you are reasonably sure your visitors can handle it. | | VERY IMPORTANT: If you are getting a blank page when compression is enabled it | means you are prematurely outputting something to your browser. It could | even be a line of whitespace at the end of one of your scripts. For | compression to work, nothing can be sent before the output buffer is called | by the output class. Do not 'echo' any values with compression enabled. |
 */
$config ['compress_output'] = FALSE;

/*
 * |-------------------------------------------------------------------------- | Master Time Reference |-------------------------------------------------------------------------- | | Options are 'local' or 'gmt'. This pref tells the system whether to use | your server's local time as the master 'now' reference, or convert it to | GMT. See the 'date helper' page of the user guide for information | regarding date handling. |
 */
$config ['time_reference'] = 'local';

/*
 * |-------------------------------------------------------------------------- | Rewrite PHP Short Tags |-------------------------------------------------------------------------- | | If your PHP installation does not have short tag support enabled CI | can rewrite the tags on-the-fly, enabling you to utilize that syntax | in your view files. Options are TRUE or FALSE (boolean) |
 */
$config ['rewrite_short_tags'] = FALSE;

/*
 * |-------------------------------------------------------------------------- | Reverse Proxy IPs |-------------------------------------------------------------------------- | | If your server is behind a reverse proxy, you must whitelist the proxy IP | addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR | header in order to properly identify the visitor's IP address. | Comma-delimited, e.g. '10.0.1.200,10.0.1.201' |
 */
$config ['proxy_ips'] = '';

$config ['rediskeys'] = array (
		"count_yestoday" => "caipiao:backend:hash:count_yestoday",
		"count_thirty" => "caipiao:backend:hash:count_thirty" 
)
;

/**
 * redis keys
 * 该数组值要和前端config值保持一致
 * 之所以在该处添加该数组是为了后台程序中用到时，不需要加载前端config去获取相应值
 */
$config ['REDIS'] = array (
		'UNIQUE_KEY' => '_unique_key:',
		'ORDERS_CHECK_START_TIME' => '_orders_check_start_time:',
		'USER_INFO' => '_user_info:',
		'CX_DATA' => '_cx_data:',
		'CX_API' => '_cx_api:',
		'CX_API_PARAMS' => '_cx_params:',
		'CX_API_SETS' => '_cx_api_sets:',
		'CACHE_TYPE' => array (
				'ticket_data_pl0' => '_cache_key0:6:1'  // key:timeout:switch
				),
		'NOTICE_RECORDS' => '_notice_records:',
		'TOTAL_WIN' => '_total_win:',
		'validChannels' => '_validChannels' 
);

$config ['OUTTIME'] = array (
		'captche' => 30,
		'cx_data' => 5 
);
$config ['MESSAGE'] = array (
		'captche' => "您的验证码为：#CODE#，{$config['OUTTIME']['captche']}分钟内有效，切勿将验证码告知他人！请及时正确输入。",
		'tick_fail' => '您的帐号#UNAME#于#MM#月#DD#日#HH#：#II#投注的#LID#出票失败，支付金额已返还您的帐户。',
		'lottery_fail' => '您的帐号#UNAME#于#MM#月#DD#日 #HH#：#II#投注的#LID#投注失败，支付金额已返还您的帐户。',
		'withdraw_succ' => '您的帐号#UNAME#于#MM#月#DD#日 #HH#：#II#提交的提款申请已处理完成，提款金额#MONEY#元，请注意查收。',
		'withdraw_fail' => '您的帐号#UNAME#于#MM#月#DD#日 #HH#：#II#提交的提款申请处理失败，请登录网站查看详情。',
		'win_prize' => '恭喜您！您的帐号#UNAME#于#MM#月#DD#日#HH#时#II#分投注的#LID#中奖#MONEY#元，已派奖到您的帐户。' 
);
/* End of file config.php */
/* Location: ./application/config/config.php */
